<?php

namespace App\Services\Llm;

/**
 * Represents token usage reported by an LLM provider.
 */
final readonly class TokenUsage
{
    /**
     * Creates a token usage value object.
     *
     * @param int $promptTokens Number of tokens used by the input messages.
     * @param int $completionTokens Number of tokens generated by the model.
     * @param int $totalTokens Total number of consumed tokens.
     */
    public function __construct(
        public int $promptTokens,
        public int $completionTokens,
        public int $totalTokens,
    ) {}

    /**
     * Creates token usage from an OpenAI-style usage array.
     *
     * @param array{
     *     prompt_tokens?: int,
     *     completion_tokens?: int,
     *     total_tokens?: int
     * } $usage Token usage data returned by the LLM provider.
     *
     * @return self
     */
    public static function fromArray(array $usage): self
    {
        return new self(
            promptTokens: (int)($usage['prompt_tokens'] ?? 0),
            completionTokens: (int)($usage['completion_tokens'] ?? 0),
            totalTokens: (int)($usage['total_tokens'] ?? 0),
        );
    }

    /**
     * Converts this value object to an OpenAI-style usage array.
     *
     * @return array{
     *     prompt_tokens: int,
     *     completion_tokens: int,
     *     total_tokens: int
     * }
     */
    public function toArray(): array
    {
        return [
            'prompt_tokens' => $this->promptTokens,
            'completion_tokens' => $this->completionTokens,
            'total_tokens' => $this->totalTokens,
        ];
    }
}
